version: "3"

volumes:
  db-data: {}

services:
  postgres:
    image: postgres:12.18
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_USER: base
      POSTGRES_PASSWORD: development
    ports:
      - "5432:5432"
    networks:
      - myapp-net
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  myapp-net:
